const jAds = //*colección 7i1i8i4 de los anuncios JSON
	`[ 	
	{
		"iads": "7i1i8i4",
		"r3A1": ["participate this Sunday, January 29, in an ecological walk in Ciudad Bolívar, IDRD, invites you"	,"Be part of our ecological walks, and discover places that will help you connect with nature."								,"This Sunday the appointment is in Ciudad Bolívar, Casona and Sierra Morena"	],
		"r3A2": ["..participa este domingo 29 de enero en una caminata ecológica en Ciudad Bolívar, IDRD, te invita"	,"Sé parte de nuestras caminatas ecológicas, y conoce lugares que te ayudarán a conectarte con la naturaleza."				,"Este domingo la cita es en Ciudad Bolívar, Casona y Sierra Morena"			],
		"r3A3": ["participez ce dimanche 29 janvier à une promenade écologique à Ciudad Bolívar, IDRD vous invite"	,"Faites partie de nos promenades écologiques et découvrez des lieux qui vous aideront à vous connecter avec la nature."	,"Ce dimanche, le rendez-vous est à Ciudad Bolívar, Casona et Sierra Morena"   	],
		"r3A4": ["1월 29일 일요일, IDRD의 Ciudad Bolívar에서 열리는 생태 산책에 여러분을 초대합니다."							,"생태 산책에 참여하고 자연과 연결하는 데 도움이 되는 장소를 발견하세요."																		,"이번 일요일 약속은 Ciudad Bolívar, Casona 및 Sierra Morena에 있습니다."   			],
		"r3Z1":	["person walking up the mountain"			,"person walking up the mountain"	,"person walking up the mountain"	],
		"r3Z2":	["persona caminando por la montaña"			,"persona caminando por la montaña"	,"persona caminando por la montaña"	],
		"r3Z3":	["personne qui monte la montagne"			,"personne qui monte la montagne"	,"personne qui monte la montagne"	],
		"r3Z4": ["산을 오르는 사람"								,"산을 오르는 사람"						,"산을 오르는 사람"						],
		"r3B1": [3,1,3],
		"r3B2": [18,16,4],
		"r3B3": 0,
		"r3B4": 1,
		"r3B5": [0,0,0],
		"r3B6": [0,0,0],
		"r3B7": [0,0,0],
		"r3B8": [0,0,0],
		"r3B9": [0,0,0],
		"r3B10": [0,0,0]
	},
	{
		"iads": "7i1i8i4",
		"r3A1": ["Hike Ciudad Bolívar, Casona and Sierra Morena. Sunday, January 29, 9:00 a.m. to 11:00 a.m."	,"Meeting point: In front of the Francisco José de Caldas District University, calle 68 bis A sur #49F-70"		,"Free registration, more information at www.idrd.gov.co and on our social networks" 		],
		"r3A2": ["..Caminata Ciudad Bolívar, Casona y Sierra Morena. Domingo 29 de enero, 9:00 a 11:00 a.m."		,"Punto de encuentro: Frente a la Universidad Distrital Francisco José de Caldas, calle 68 bis A sur #49F-70"	,"Inscripción gratuita, mayor información en www.idrd.gov.co y en nuestras redes sociales"	],
		"r3A3": ["Randonnée Ciudad Bolívar, Casona et Sierra Morena. Dimanche 29 janvier de 9h00 à 11h00"		,"Point de rencontre: Devant l\'Université du district Francisco José de Caldas, calle 68 bis A sur #49F-70"	,"Inscription gratuite, plus d\'informations sur www.idrd.gov.co et sur nos réseaux sociaux"	],
		"r3A4": ["Ciudad Bolívar, Casona 및 Sierra Morena를 하이킹하십시오. 1월 29일 일요일 오전 9시 ~ 오전 11시"			,"만남의 장소: Francisco José de Caldas District University 앞, calle 68 bis A sur #49F-70."						,"Inscription gratuite, plus d\'informations sur www.idrd.gov.co et sur nos réseaux sociaux"	],
		"r3Z1":	["Hike Ciudad Bolívar, Casona and Sierra Morena. Sunday, January 29, 9:00 a.m. to 11:00 a.m."	," Meeting point: In front of the Francisco José de Caldas District University, calle 68 bis A sur #49F-70."	,"Free registration, more information at www.idrd.gov.co and on our social networks" 		],
		"r3Z2":	["Caminata Ciudad Bolívar, Casona y Sierra Morena. Domingo 29 de enero, 9:00 a 11:00 a.m."		,"Punto de encuentro: Frente a la Universidad Distrital Francisco José de Caldas, calle 68 bis A sur #49F-70."	,"Inscripción gratuita, mayor información en www.idrd.gov.co y en nuestras redes sociales"	],
		"r3Z3":	["Randonnée Ciudad Bolívar, Casona et Sierra Morena. Dimanche 29 janvier de 9h00 à 11h00"		," Point de rencontre: Devant l\'Université du district Francisco José de Caldas, calle 68 bis A sur #49F-70."	,"Inscription gratuite, plus d\'informations sur www.idrd.gov.co et sur nos réseaux sociaux"	],
		"r3Z4": ["Randonnée Ciudad Bolívar, Casona et Sierra Morena. Dimanche 29 janvier de 9h00 à 11h00"		," Point de rencontre: Devant l\'Université du district Francisco José de Caldas, calle 68 bis A sur #49F-70."	,"Inscription gratuite, plus d\'informations sur www.idrd.gov.co et sur nos réseaux sociaux"	],
		"r3B1": [2,2,3],
		"r3B2": [33,35,5],
		"r3B3": 0,
		"r3B4": 1,
		"r3B5": [0,0,0],
		"r3B6": [0,0,0],
		"r3B7": [0,0,0],
		"r3B8": [0,0,0],
		"r3B9": [0,0,0],
		"r3B10": [0,0,0] 
	},
	{
		"iads": "7i1i8i4",
		"r3A1": ["invitation to sports event, physical activity, blah, blah, blah, blah"],
		"r3A2": ["..invitación a evento deportivo, actividad física, bla, bla, bla, bla"],
		"r3A3": ["invitation à un événement sportif, activité physique, bla, bla, bla, bla"],
		"r3A4": ["스포츠 행사 초대, 신체 활동, 어쩌구 저쩌구 어쩌구 저쩌구"],
		"r3Z1":	["invitation to sports event, physical activity, blah, blah, blah, blah"],
		"r3Z2":	["invitación a evento deportivo, actividad física, bla, bla, bla, bla"],
		"r3Z3":	["invitation à un événement sportif, activité physique, bla, bla, bla, bla"],
		"r3Z4": ["invitation à un événement sportif, activité physique, bla, bla, bla, bla"],
		"r3B1": [2],
		"r3B2": [31],
		"r3B3": 0,
		"r3B4": 1,
		"r3B5": [0],
		"r3B6": [0],
		"r3B7": [0],
		"r3B8": [0],
		"r3B9": [0],
		"r3B10": [0]
	},
	{
		"iads": "7i1i8i4",
		"r3A1": ["invitation to General Assembly, blah, blah, blah"	,"abece 1"	,"abece 2"],
		"r3A2": ["..invitación a Asamblea General, bla, bla, bla" 		,"abece 1"	,"abece 2"],
		"r3A3": ["invitation à l\'Assemblée générale, bla, bla, bla"	,"abece"	,"abece"],
		"r3A4": ["총회 초대, 어쩌구 저쩌구"									,"abece"	,"abece"],
		"r3Z1":	["invitation to General Assembly, blah, blah, blah, blah", "abece 1","abece 2"],
		"r3Z2":	["invitación a Asamblea General, bla, bla, bla, bla" ,"abece 1","abece 2"],
		"r3Z3":	["invitation à l\'Assemblée générale, bla, bla, bla, bla","abece","abece"],
		"r3Z4": ["invitation à l\'Assemblée générale, bla, bla, bla, bla","abece","abece"],
		"r3B1": [2,1,1],
		"r3B2": [37,15,16],
		"r3B3": 0,
		"r3B4": 1,
		"r3B5": [0,0,0],
		"r3B6": [0,0,0],
		"r3B7": [0,0,0],
		"r3B8": [0,0,0],
		"r3B9": [0,0,0],
		"r3B10": [0,0,0]
	},
	{
		"iads": "7i1i8i4",
		"r3A1": ["open calls by the ICT Ministry for university students, teachers, women, people with disabilities, companies and entrepreneurs in the country"								,"Those interested should enter the ministry\'s website www.mintic.gov.co to consult the details of each project and the closing of the calls."],
		"r3A2": ["..convocatorias abiertas por el MinTIC para universitarios, docentes, mujeres, personas con discapacidad, empresas y emprendedores del país"									,"Los interesados deberán ingresar a la página web del ministerio www.mintic.gov.co a consultar los detalles de cada proyecto y los cierres de las convocatorias."],
		"r3A3": ["appels ouverts du ministère des TIC pour les étudiants universitaires, les enseignants, les femmes, les personnes handicapées, les entreprises et les entrepreneurs du pays"	,"Les personnes intéressées doivent entrer sur le site Web du ministère www.mintic.gov.co pour consulter les détails de chaque projet et la clôture des appels."],
		"r3A4": ["국내 대학생, 교사, 여성, 장애인, 기업 및 기업가를 대상으로 정보통신부가 공개 모집"																												,"Les personnes intéressées doivent entrer sur le site Web du ministère www.mintic.gov.co pour consulter les détails de chaque projet et la clôture des appels."],
		"r3Z1":	["open calls by the ICT Ministry for university students, teachers, women, people with disabilities, companies and entrepreneurs in the country"								,"Those interested should enter the ministry\'s website www.mintic.gov.co to consult the details of each project and the closing of the calls."],
		"r3Z2":	["convocatorias abiertas por el MinTIC para universitarios, docentes, mujeres, personas con discapacidad, empresas y emprendedores del país"									,"Los interesados deberán ingresar a la página web del ministerio www.mintic.gov.co a consultar los detalles de cada proyecto y los cierres de las convocatorias."],
		"r3Z3":	["appels ouverts du ministère des TIC pour les étudiants universitaires, les enseignants, les femmes, les personnes handicapées, les entreprises et les entrepreneurs du pays"	,"Les personnes intéressées doivent entrer sur le site Web du ministère www.mintic.gov.co pour consulter les détails de chaque projet et la clôture des appels."],
		"r3Z4": ["appels ouverts du ministère des TIC pour les étudiants universitaires, les enseignants, les femmes, les personnes handicapées, les entreprises et les entrepreneurs du pays"	,"Les personnes intéressées doivent entrer sur le site Web du ministère www.mintic.gov.co pour consulter les détails de chaque projet et la clôture des appels."],
		"r3B1": [3,2],
		"r3B2": [3,36],
		"r3B3": 0,
		"r3B4": 1,
		"r3B5": [0,0],
		"r3B6": [0,0],
		"r3B7": [0,0],
		"r3B8": [0,0],
		"r3B9": [0,0],
		"r3B10": [0,0]
	}
]`;